package com.astraform.classifier.model;

public enum FormType {
    PAN_APPLICATION,
    AADHAAR_ENROLLMENT,
    DRIVING_LICENSE_APPLICATION,
    PASSPORT_APPLICATION,
    INCOME_TAX_RETURN,
    VISA_APPLICATION,
    BANK_KYC,
    PROPERTY_REGISTRATION,
    VEHICLE_REGISTRATION,
    BIRTH_CERTIFICATE_APPLICATION,
    VOTER_ID_APPLICATION,
    FORM_16,
    GST_RETURN,
    RATION_CARD_APPLICATION,
    UNKNOWN
}
